---
- name: Test user is present
  hosts: LINUX
  become: true

  vars:
    myuser: "logintest"

  tasks:
  - name: testing user {{ myuser }} is present
    ansible.builtin.user:
      name: "{{ myuser }}"
      state: "absent"

