---
- name: Test user is present
  hosts: LINUX
  become: true

  vars:
    myuser: "ftpq"

  tasks:
  - name: testing user {{ myuser }} no present (ok absent)
    ansible.builtin.user:
      name: "{{ myuser }}"
      state: "absent"
      #state: "present" OK cuando existe

