---
- name: Test user is present
  hosts: WINDOWS
  become: false

  vars:
    myuser: "logintest"
    mypass: "Quiter.2022"

  tasks:
   - name: Adding user {{ myuser }} 
     ansible.windows.win_user:
       name: "{{myuser}}"
       state: present
       password: "{{mypass}}"
       groups:
         - Usuarios
         - GQUITER
