---
- name: lin os version demo
  hosts: WINDOWS
  become: false
  gather_facts: yes
  
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"
    - "{{ ansible_hostname }}"
    - "{{ ansible_interfaces }}"
